# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp
	pod "Repro"
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Google/Analytics'
	pod 'ReachabilitySwift', '~> 3'
	pod 'Alamofire', '~> 4.0’
end
